name: CI - Bats Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  bats-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install bats
      - name: Install bats
        run: |
          sudo apt-get update
          sudo apt-get install -y bats

      # Step 3: Set up src directory for transferred files
      - name: Set up src directory for transferred files
        run: |
          mkdir -p src
          cp tests/testFiles/* src/

      # Step 4: Run bats tests
      - name: Run bats tests
        run: bats tests/client_tests.sh